"""SilentCX commercial catalog: packages & add-ons. Single source used everywhere."""

PACKAGES = [
    {
        "id": "pkg_essential",
        "key": "essential",
        "name": "SilentCX Essential",
        "price": 1249000,
        "outlet_limit": 1,
        "visits": 1,
        "purchase_allowance": 150000,
        "recommended": False,
        "active": True,
        "tagline": "Foundational mystery visit & CX snapshot",
        "indicators": "~30 Audit Indicators",
        "features": [
            "1 Outlet", "1 Mystery Visit", "~30 Audit Indicators",
            "Greeting & Service Attitude", "Product Knowledge", "Order Accuracy",
            "Service Speed", "Cleanliness & Ambience", "Upselling / Closing",
            "Overall CX Score", "3–5 Key Findings", "Quick Recommendations",
            "PDF Audit Report", "15-Minute Result Debrief",
            "Purchase Allowance up to IDR 150,000 per visit",
        ],
    },
    {
        "id": "pkg_insight",
        "key": "insight",
        "name": "SilentCX Insight",
        "price": 1749000,
        "outlet_limit": 1,
        "visits": 1,
        "purchase_allowance": 150000,
        "recommended": True,
        "active": True,
        "tagline": "Deep diagnostic with evidence & SOP compliance",
        "indicators": "~50–70 Audit Indicators",
        "features": [
            "1 Outlet", "1 Mystery Visit", "~50–70 Audit Indicators",
            "All Essential Assessment Areas", "SOP Compliance Check",
            "Customer Journey Evaluation", "Evidence & Documentation",
            "Severity Classification", "Gap Analysis", "5–10 Priority Findings",
            "Actionable Recommendations", "Management Summary", "Detailed Audit Report",
            "30-Minute Consultation", "Purchase Allowance up to IDR 150,000 per visit",
        ],
    },
    {
        "id": "pkg_performance",
        "key": "performance",
        "name": "SilentCX Performance",
        "price": 3749000,
        "outlet_limit": 5,
        "visits": 1,
        "purchase_allowance": 150000,
        "recommended": False,
        "active": True,
        "tagline": "Multi-outlet benchmarking & executive intelligence",
        "indicators": "~50–70 Indicators × Outlets",
        "price_tiers": [
            {"outlets": 3, "price": 3749000},
            {"outlets": 4, "price": 4599000},
            {"outlets": 5, "price": 5399000},
        ],
        "features": [
            "3–5 Outlets", "1 Visit per Outlet", "All Insight Features",
            "Multi-Outlet Audit", "Branch Comparison", "Outlet Ranking",
            "SOP Compliance Comparison", "CX Benchmarking", "Red Flag Identification",
            "Cross-Outlet Trend Analysis", "Management Recommendations",
            "Executive Summary", "Management Review",
            "Purchase Allowance up to IDR 150,000 per visit",
        ],
    },
]

ADDONS = [
    {"id": "addon_outlet", "key": "additional_outlet", "name": "Additional Outlet",
     "description": "Add an extra outlet to the audit project.", "pricing_type": "fixed",
     "price": 1099000, "unit": "per outlet", "behavior": "enhance", "active": True,
     "requires_approval": False, "applicable_packages": ["essential", "insight", "performance"]},
    {"id": "addon_visit", "key": "additional_visit", "name": "Additional Visit",
     "description": "Schedule an extra mystery visit for an outlet.", "pricing_type": "fixed",
     "price": 749000, "unit": "per visit", "behavior": "enhance", "active": True,
     "requires_approval": False, "applicable_packages": ["essential", "insight", "performance"]},
    {"id": "addon_reaudit", "key": "re_audit", "name": "Re-Audit",
     "description": "Follow-up audit cycle to verify improvement.", "pricing_type": "fixed",
     "price": 899000, "unit": "per outlet", "behavior": "module", "active": True,
     "requires_approval": True, "applicable_packages": ["insight", "performance"]},
    {"id": "addon_competitor", "key": "competitor_benchmark", "name": "Competitor Benchmark Audit",
     "description": "Benchmark your outlet against a direct competitor.", "pricing_type": "fixed",
     "price": 1299000, "unit": "per competitor", "behavior": "module", "active": True,
     "requires_approval": False, "applicable_packages": ["insight", "performance"]},
    {"id": "addon_questionnaire", "key": "custom_questionnaire", "name": "Custom Questionnaire",
     "description": "Tailored audit questions & weighting for your brand.", "pricing_type": "starting_from",
     "price": 650000, "unit": "per project", "behavior": "module", "active": True,
     "requires_approval": True, "applicable_packages": ["insight", "performance"]},
    {"id": "addon_consultation", "key": "additional_consultation", "name": "Additional Consultation",
     "description": "Extra strategy session with a CX consultant.", "pricing_type": "fixed",
     "price": 499000, "unit": "per session", "behavior": "module", "active": True,
     "requires_approval": False, "applicable_packages": ["essential", "insight", "performance"]},
    {"id": "addon_priority", "key": "priority_report", "name": "Priority / Express Report",
     "description": "Fast-tracked report delivery.", "pricing_type": "fixed",
     "price": 599000, "unit": "per project", "behavior": "status", "active": True,
     "requires_approval": False, "applicable_packages": ["essential", "insight", "performance"]},
    {"id": "addon_outofcity", "key": "out_of_city", "name": "Out-of-City Assignment",
     "description": "Logistics for outlets outside the base city.", "pricing_type": "quotation",
     "price": 0, "unit": "by quotation", "behavior": "status", "active": True,
     "requires_approval": True, "applicable_packages": ["essential", "insight", "performance"]},
    {"id": "addon_excess", "key": "excess_purchase", "name": "Excess Purchase Reimbursement",
     "description": "Reimburse purchase above IDR 150,000 allowance.", "pricing_type": "actual",
     "price": 0, "unit": "actual cost", "behavior": "billing", "active": True,
     "requires_approval": False, "applicable_packages": ["essential", "insight", "performance"]},
]

SCORE_THRESHOLDS = [
    {"min": 90, "label": "Excellent", "key": "excellent"},
    {"min": 80, "label": "Good", "key": "good"},
    {"min": 70, "label": "Needs Attention", "key": "needs_attention"},
    {"min": 60, "label": "Poor", "key": "poor"},
    {"min": 0, "label": "Critical", "key": "critical"},
]
